name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v4

    - name: Ubuntu setup
      run: /bin/sh -c "$GITHUB_WORKSPACE/.github/workflows/setup-ubuntu.sh"

    - name: configure
      run: meson setup build

    - name: Compile
      run: ninja -C build

    - name: Run distcheck
      run: meson dist -C build --allow-dirty
